# Generated by Django 4.2.3 on 2025-05-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onlinecourse", "0002_choice_submission_question_choice_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="is_true",
            new_name="is_correct",
        ),
        migrations.AlterField(
            model_name="choice",
            name="content",
            field=models.CharField(max_length=200),
        ),
    ]
